### ISSUE TITLE
tokenize() on null

### ISSUE THREAD

**Issue by ashudb70** [APISENSE/android-network-measures#7]
after downloading and trying to import as module it gives and error cannot invoke method tokenize() on null object.
IN GRADLE

**Comment by aveuiller** [comment]
The project is defining a [global variable version](https://github.com/APISENSE/android-network-measures/blob/develop/build.gradle#L35) which is called to compute an Android version code [using the method tokenize](https://github.com/APISENSE/android-network-measures/blob/4bb837ff835645d86b418a425f07ef02bcaa5184/measures/build.gradle#L21).

If you imported the module without providing a _version_ variable, it will fail inevitably. But it is harmless to replace the `computeVersionCode` method with a static value if that's what you want.
